name: ButtonControl
main: me.johni0702.ButtonControl.ButtonControl
version: 2.2
author: johni0702
description: >
             Switch weather or time by pressing a button
commands:
  buttoncontrol:
    description: Sets the sunny button
    usage: /<command> [sunny/rain/thunder/day/night]
    aliases: [bc]